### ISSUE TITLE
Who is our audience for this playbook?

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/agile-playbook#2]
At our last session on Friday, we discussed identifying our key audience(s). This will help us focus our content and decide what's most important to cover.

Here's just a braindump of possible audiences, not in any particular order:

Internal
- Dev and design practitioners of agile within the cfpb
- Product owners / stakeholders / potential collaborators across the bureau
- New members of the dev and design team who may or may not be familiar with agile

External
- Other designers and developers in government interested in or currently practicing agile
- Leadership within other government agencies considering adopting agile
- Tech-workers in the public interested in how we work
- Developers and designers who might be interested in working at the cfpb

Who else? Thoughts about which audiences we want to focus on serving (or focus on serving first)?

**Comment by mistergone** [comment]
I think we can keep all the audiences in mind as we write this documentation and discuss it, but yes, at some point Real Soon we should decided the main audience.

**Comment by leejenni** [comment]
For internal stakeholders, I think we can also include other teams within the Bureau who may want to adapt Agile (e.g., CR?)

**Comment by marteki** [comment]
That list is super through. I can't think of other audiences we might be trying to reach.

For a focus, what if we chose one internal and one external group to focus on?

Either: product owners/stakeholders/collaborators within the bureau, as well as leadership in other agencies
Or: New devs and designers here, as well as other designers and devs across the government

**Comment by stephanieosan** [comment]
We made audience decisions during our meeting today!

Primary internal audience: Collaborators within the Bureau (product owners, stakeholders collaborators)

Primary external audience: Leadership and practitioners within other government agencies considering adopting or currently practicing agile
